name: Build And Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v2.4.0
        with:
          version: '14.x'

      - name: npm ci
        run: npm ci


      - name: npm run build
        run: npm run build:p

      - name: deploy project to server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.deploy_server }}
          USERNAME: ${{ secrets.deploy_user }}
          PASSWORD: ${{ secrets.deploy_password }}
          PORT: ${{ secrets.deploy_port }}
        with:
          source: "./dist/house-of-gate/"
          target: ${{ secrets.deploy_target }}
          strip_components: 3 # this is important I'm pretty sure
          rm: true #clean target folder before copying
          timeout: 60s
          command_timeout: 1m
