name: Build And Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build:p

      - name: deploy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "./dist/house-of-gate/browser/"
          target: ${{ secrets.DEPLOY_TARGET }}
          strip_components: 3 # this is important I'm pretty sure
          rm: true #clean target folder before copying
          timeout: 60s
          command_timeout: 1m
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
